apps/dashboard/urls.py
from django.urls import path
from . import views
from . import views_api

urlpatterns = [
    path('dashboard/', views.DashBoard.as_view(), name='dashboard'),

    path('add-employee/', views.AddEmployees.as_view(), name='add_employee'),
    path('update-employee/<int:pk>/', views.EmployeeUpdate.as_view(), name='update_employee'),
    path('delete-employee/', views.EmployeeDelete.as_view(), name='delete_employee'),
    path('employee-list/', views.EmployeeList.as_view(), name='employee_list'),
    path('employee-detail/<int:pk>/', views.EmployeeDetail.as_view(), name='employee_detail'),

    path('add-techtool/', views.AddTechTools.as_view(), name='add_techtool'),
    path('update-techtool/', views.UpdateTechTools.as_view(), name='update_techtool'),
    path('delete-techtool/', views.DeleteTechTools.as_view(), name='delete_techtool'),
    path('techtool-list/', views.TechToolList.as_view(), name='techtool_list'),

    path('assign-tool/', views.AssignTools.as_view(), name='assign_tool'),
    path('tool-issue/', views.ToolIssued.as_view(), name='tools_issued'),

    # urls for api
    path('toollist-api/', views_api.TechToolListApi.as_view(), name="techtoollist_api"),
    path('tooldetail-api/<int:pk>/', views_api.TechToolDetailApi.as_view(), name="tooldetail_api"),
    path('assign-list-api/', views_api.AssignToolListApi.as_view(), name="assign_list_api"),
    path('assign-create-api/', views_api.AssignToolCreateApi.as_view(), name="assign_create_api"),



]

techbox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views


def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.dashboard.urls')),
    path('', include('apps.account.urls')),
    path('sentry-debug/', trigger_error),
    path('api-token-auth/', views.obtain_auth_token),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),



]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Dashboard/models.py
from django.db import models
from phone_field import PhoneField

# Create your models here.
DESIGNATION = (
    ('PYTHON TEAM LEADER', 'python team leader'),
    ('PYTHON SENIOR DEV', 'python senior developer'),
    ('PYTHON JUNIOR DEV', 'python junior developer'),
    ('PYTHON TRAINEE DEV', 'python trainee developer'),

    ('ROR TEAM LEADER', 'ror team leader'),
    ('ROR SENIOR DEV', ' ror senior developer'),
    ('ROR JUNIOR DEV', 'ror junior developer'),
    ('ROR TRAINEE DEV', 'ror trainee developer'),

    ('FRONTEND TEAM LEADER', 'frontend team leader'),
    ('FRONTEND SENIOR DEV', 'frontend senior developer'),
    ('FRONTEND JUNIOR DEV', 'frontend junior developer'),
    ('FRONTEND TRAINEE DEV', 'frontend trainee developer'),
)


class TechTool(models.Model):
    name = models.CharField(max_length=200)
    quantity = models.IntegerField(default=0)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Employee(models.Model):
    name = models.CharField(max_length=100)
    designation = models.CharField(choices=DESIGNATION, max_length=100)
    address = models.CharField(max_length=150)
    mobile = PhoneField(blank=True, help_text='Contact mobile number')
    email = models.EmailField()
    date_of_birth = models.DateField()

    def __str__(self):
        return self.name


class Schedule(models.Model):
    empName = models.ForeignKey(Employee, on_delete=models.CASCADE)
    techTool = models.ForeignKey(TechTool, on_delete=models.CASCADE)
    borrowTime = models.DateTimeField(auto_now_add=True)
    SubmitDate = models.DateTimeField()

    def __str__(self):
        return self.techTool.name

apps/dashboard/models.py
import datetime

from django.db import models
from phone_field import PhoneField



# Create your models here.
DESIGNATION = (
    ('1', ' team leader'),
    ('2', ' senior developer'),
    ('3', ' junior developer'),
    ('4', ' trainee developer'),
)


class TechTool(models.Model):
    name = models.CharField(max_length=200)
    status = models.BooleanField(default=True, blank=True, null=True)

    def __str__(self):
        return self.name


class Employee(models.Model):
    name = models.CharField(max_length=100)
    image = models.FileField(default='img/undraw_profile.svg', upload_to='img/', blank=True, null=True)
    designation = models.CharField(choices=DESIGNATION, max_length=100)
    address = models.CharField(max_length=150)
    mobile = PhoneField(blank=True, help_text='Contact mobile number')
    email = models.EmailField()
    date_of_birth = models.DateField()

    def __str__(self):
        return self.name


class ToolsIssue(models.Model):
    empName = models.ForeignKey(Employee, on_delete=models.CASCADE)
    techTool = models.ForeignKey(TechTool, on_delete=models.CASCADE)
    borrowTime = models.DateTimeField(auto_now_add=True)
    submitDate = models.DateTimeField()
    timeOut = models.BooleanField(default=False)

    def __str__(self):
        return self.techTool.name

Dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .models import *


def index(request):
    return HttpResponse("tech Box")


class AddEmployees(View):
    def get(self, request):
        print(DESIGNATION)
        designations = []
        for d in DESIGNATION:
            designations.append(d[1])
        return render(request, 'dashboard/employee_add.html', {'designations': designations})

    def post(self, request, *args, **kwargs):
        try:
            designations = []
            for d in DESIGNATION:
                designations.append(d[1])
            name = request.POST.get('name')
            designation = request.POST.get('designation')
            address = request.POST.get('address')
            mobile = request.POST.get('mobile')
            email = request.POST.get('email')
            date_of_birth = request.POST.get('dob')
            print(request.POST)

            employee = Employee.objects.create(name=name, designation=designation, address=address,
                                               mobile=mobile, email=email, date_of_birth=date_of_birth)
            return render(request, 'dashboard/employee_add.html', {'employee': employee, 'designations': designations})

        except Exception as e:
            print(e)
        return render(request, 'dashboard/employee_add.html')


class AddTechTools(View):

    def get(self,request):

        return render(request, 'dashboard/techtool_add.html')

    # def post(self, request):
    #     name = request.POST.get('name')
    #     quantity = request.POST.get('quantity')
    #     techtool = TechTool.objects.create(name=name, quantity=quantity)
    #
    #     return HttpResponse('tool added')

apps/dashboard/views.py
import pytz
import datetime

ist = pytz.timezone("Asia/Calcutta")

from django.views import View
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .forms import EmployeeForm, TechToolForm, AssignToolForm

from .models import *
from apps.dashboard.task import status_change, mail_to_timeover_employee, mailtoassignemployee, remind_to_employee


class DashBoard(View):

    @method_decorator(login_required(login_url="/"))
    def get(self, request):

        data = {}
        employees = Employee.objects.all()
        data['employees'] = employees
        tools = TechTool.objects.all()
        data['numberofemp'] = employees.count()
        data['numberoftools'] = tools.count()
        issued_tools = ToolsIssue.objects.all()
        data['issued_tools'] = issued_tools
        data['tools'] = tools

        trainee = 0
        tl = 0
        jd = 0
        sd = 0
        data['assigned_to_tl'] = 0
        data['assigned_to_sd'] = 0
        data['assigned_to_jd'] = 0
        data['assigned_to_trainee'] = 0
        issuedcount = issued_tools.count()

        for i in issued_tools:
            if i.empName.designation == '1':
                tl += 1

            elif i.empName.designation == '2':
                sd += 1

            elif i.empName.designation == '3':
                jd += 1

            elif i.empName.designation == '4':
                trainee += 1

        if trainee > 0:
            data['assigned_to_trainee'] = ((trainee * 100) / issuedcount)
        if jd > 0:
            data['assigned_to_jd'] += ((jd * 100) // issuedcount)
        if sd > 0:
            data['assigned_to_sd'] += ((sd * 100) // issuedcount)
        if tl > 0:
            data['assigned_to_tl'] += ((tl * 100) // issuedcount)

        return render(request, 'dashboard/dashboard.html', data)


class AddTechTools(View):

    def post(self, request):
        data = {}
        print(request.POST)
        add_too_form = TechToolForm(request.POST)
        if add_too_form.is_valid():
            tool = add_too_form.cleaned_data['name']

            add_too_form.save()
            newtool = TechTool.objects.last()
            print(newtool.id)
            data['newtool'] = newtool

        return render(request, 'dashboard/newtool.html', data)

    # def get(self, request):
    #     form = TechToolForm
    #     return render(request, 'dashboard/techtool_add.html', {'form': form})


class TechToolList(View):

    @method_decorator(login_required(login_url="/login/"))
    def get(self, request):
        data = {}
        form = TechToolForm
        tools = TechTool.objects.all()
        data['tools'] = tools
        data['form'] = form
        return render(request, 'dashboard/techtool-list.html', data)


class UpdateTechTools(View):

    def post(self, request):
        data = {}
        try:
            pk = request.POST.get("id")
            print(request.POST)
            tool = TechTool.objects.get(id=pk)
            print(tool)

            status = request.POST.get('status')
            print(status)
            if status == 'on':
                tool.name = request.POST.get('name')
                tool.status = True
                tool.save()
                data['newtool'] = tool


            else:
                print(status)
                tool.name = request.POST.get('name')
                tool.status = False
                tool.save()
                data['newtool'] = tool
        except Exception as e:
            print(e)
        return render(request, 'dashboard/newtool.html', data)
    #
    #
    # def get(self, request):
    #
    #     form = TechToolForm()
    #     return render(request, 'dashboard/update-tool.html', {'form': form})


class DeleteTechTools(View):

    def post(self, request):
        tool_id = request.POST.get('id')
        print(tool_id)
        tool = TechTool.objects.get(id=tool_id)

        tool.delete()

        return redirect('techtool_list')


# Employee views


class AddEmployees(View):

    def get(self, request):
        form = EmployeeForm
        return render(request, 'dashboard/add-employee.html', {'form': form})

    def post(self, request, *args, **kwargs):
        try:
            data = {}
            emp_form = EmployeeForm(request.POST, request.FILES)
            if emp_form.is_valid():
                emp_form.save()
                messages.success(request, 'Employee Add Successfully ')
                newemp = Employee.objects.last()
                print(newemp.id)
                data['newemp'] = newemp

                return render(request, 'dashboard/newempdata.html', data)
            else:
                messages.error(request, "please fill correct details")
                return redirect('employee_list')

        except Exception as e:
            print(e)
        return render(request, 'dashboard/employee-list.html')


class EmployeeList(View):

    @method_decorator(login_required(login_url="/login/"))
    def get(self, request):
        data = {}
        employees = Employee.objects.all()
        data['employees'] = employees
        data['form'] = EmployeeForm

        return render(request, 'dashboard/employee-list.html', data)


class EmployeeDetail(View):

    @method_decorator(login_required(login_url="/login/"))
    def get(self, request, pk):
        data = {}
        employee = Employee.objects.get(pk=pk)
        data['employee'] = employee

        return render(request, 'dashboard/employee-profile.html', data)


class EmployeeUpdate(View):

    def get(self, request, pk):
        form = EmployeeForm
        return render(request, 'dashboard/update-employee.html', {'form': form})

    @method_decorator(login_required(login_url="/login/"))
    def post(self, request, pk):

        employee = Employee.objects.get(id=pk)
        emp_upd_form = EmployeeForm(request.POST, request.FILES, instance=employee)
        if emp_upd_form.is_valid():
            emp_upd_form.save()
            return redirect('employee_list')
        else:
            return HttpResponse("update not valid ")


class EmployeeDelete(View):

    @method_decorator(login_required(login_url="/login/"))
    def post(self, request):
        data = {}
        pk = request.POST.get('id')
        employee = Employee.objects.get(pk=pk)
        employee.delete()
        messages.success(request, 'Employee Delete Successfully ')

        return redirect(reverse('employee_list'))


class AssignTools(View):
    def post(self, request, *args, **kwargs):
        ist = pytz.timezone("Asia/Calcutta")
        assign_form = AssignToolForm(request.POST)

        if assign_form.is_valid():
            emp = assign_form.cleaned_data['empName']
            tool = assign_form.cleaned_data['techTool']
            employee = Employee.objects.get(id=emp.id)
            techtool = TechTool.objects.get(id=tool.id)

            print(employee, techtool)
            t_id = request.POST.get('techTool')
            min_date = ist.localize(datetime.datetime.now())
            tool = TechTool.objects.get(id=t_id)
            submitdate = request.POST.get('submitDate')

            format_iso_now = min_date.isoformat()

            if (tool.status == False):
                messages.error(request, "tool not available")
                return redirect('tools_issued')

            elif submitdate <= format_iso_now:
                print("hi elif")
                messages.error(request, "Past date or time not allowed ")
                return redirect('tools_issued')
            else:
                try:

                    assign_form.save()
                    subject = f'Hello {employee.name}  your {techtool.name}  Issued '
                    message = f'Hi  your techtool- {techtool.name} has been Issued Please collect from office if you already ' \
                              f'collect then skip this mail Have A Good !'
                    recipient_list = [employee.email, ]
                    mailtoassignemployee.delay(subject, message, recipient_list)

                    messages.success(request, "tool are issued")

                    return redirect('tools_issued')
                except Exception as e:
                    print(e)
                finally:
                    remind_to_employee.apply_async(countdown=60)
                    bdate = ToolsIssue.objects.latest('borrowTime')
                    a = bdate.borrowTime
                    b = bdate.submitDate
                    c = (b - a).total_seconds()
                    print(c)
                    subject = f'Hello {employee.name} time over'
                    message = f'Hi your techtool- {techtool.name} Usage Time is Expired Please Submit {techtool.name}  ' \
                              f'in office if you already Submit then skip this mail Have A Good !'
                    recipient_list = [employee.email, ]
                    mail_to_timeover_employee.apply_async((subject, message, recipient_list), countdown=c)
        else:
            return HttpResponse("no tool issued")

    def get(self, request):
        assign_from = AssignToolForm
        return render(request, 'dashboard/assign-tool.html', {'assign_from': assign_from})


class ToolIssued(View):

    def get(self, request):
        assign_from = AssignToolForm

        status_change()

        issued_tools = ToolsIssue.objects.all()
        # d = datetime.datetime.now().astimezone().strftime("%Y-%m-%dT%H:%M:%S %z")
        # print(d)
        data = {'issued_tools': issued_tools, 'assign_from': assign_from}

        return render(request, 'dashboard/tool-issue.html', data)

templates/dashboard/message.html
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible"
         role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <p class="h6  mb-4"> {{ message }}</p>
    </div>
{% endfor %}

templates/dashboard/newempdata.html
<tr>
    <td>{{ newemp.name }}</td>
    <td> {{ newemp.get_designation_display }}</td>
    <td>{{ newemp.address }}</td>
    <td>{{ newemp.mobile }}</td>
    <td>{{ newemp.email }}</td>
    <td>{{ newemp.date_of_birth }}</td>
    <td>
        <button type="button" class="btn btn-primary"
                data-id="{{ newemp.id }}" id="view-emp-btn"
                data-toggle="modal"
                data-target="#empModal{{ newemp.id }}">view profile
        </button>
          <!-- Modal -->
        <div class="modal fade bd-example-modal-lg"
             id="empModal{{ newemp.id }}" tabindex="-1" role="dialog"
             aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Employee Profile</h5>
                        <button type="button" class="close" data-dismiss="modal"
                                aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        <div class="container">
                            <div class="main-body">

                                <br>
                                <br>
                                <br>

                                <div class="row gutters-sm">
                                    <div class="col-md-4 mb-3">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="d-flex flex-column align-items-center text-center">
                                                    <img src="{{ newemp.image.url }}"
                                                         alt="Admin"
                                                         class="rounded-circle"
                                                         width="150">
                                                    <div class="mt-3">

                                                        <p class="text-secondary mb-1">{{ newemp.designation }}</p>
                                                        <p class="text-muted font-size-sm">{{ newemp.address }}</p>
                                                        <a href="{% url 'update_employee' newemp.id %}">
                                                            <button class="btn btn-warning">
                                                                Update
                                                            </button>
                                                        </a>
                                                        <button class="btn btn-outline-danger"
                                                                id="emp-del-btn"
                                                                data-id="{{ newemp.id }}">
                                                            Remove
                                                        </button>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-md-8">
                                        <div class="card mb-3">
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-sm-3">
                                                        <h6 class="mb-0">Full
                                                            Name</h6>
                                                    </div>
                                                    <div class="col-sm-9 text-secondary">
                                                        {{ newemp.name }}
                                                    </div>
                                                </div>
                                                <hr>
                                                <div class="row">
                                                    <div class="col-sm-3">
                                                        <h6 class="mb-0">
                                                            Email</h6>
                                                    </div>
                                                    <div class="col-sm-9 text-secondary">
                                                        {{ newemp.email }}
                                                    </div>
                                                </div>
                                                <hr>
                                                <div class="row">
                                                    <div class="col-sm-3">
                                                        <h6 class="mb-0">
                                                            Mobile</h6>
                                                    </div>
                                                    <div class="col-sm-9 text-secondary">
                                                        {{ newemp.mobile }}
                                                    </div>
                                                </div>
                                                <hr>
                                                <div class="row">
                                                    <div class="col-sm-3">
                                                        <h6 class="mb-0">
                                                            Address</h6>
                                                    </div>
                                                    <div class="col-sm-9 text-secondary">
                                                        {{ newemp.address }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary"
                                data-dismiss="modal">Close
                        </button>

                    </div>
                </div>
            </div>
        </div>
    </td>
</tr>

templates/dashboard/tool-issue.html
{% extends 'base.html' %}
{% block content %}

    <!-- Page Wrapper -->
    <div id="wrapper">

        {% include 'dashboard/sidebar.html' %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">


                {% include 'dashboard/navbar.html' %}

                <!-- Begin Page Content -->
                <div class="container-fluid">


                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Assigned Tools</h1>

                    {% for message in messages %}

                        <div class="alert {{ message.tags }} alert-dismissible"
                             role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <p class="h6  mb-4"> {{ message }}</p>


                        </div>
                    {% endfor %}
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                           <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" style=" background-image: linear-gradient(to right, darkslategray,#1a202c)">
  Assign Tool
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header text-light"  style=" background-image: linear-gradient(to right,#1a202c,darkslategray)">
        <h5 class="modal-title " id="exampleModalLongTitle">Assign Tools</h5>
        <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close" >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form method="post" action="{% url 'assign_tool' %}">
              {%  csrf_token %}
               {{ assign_from.as_p }}


      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn  text-light" style=" background-image: linear-gradient(to right,#1a202c,darkslategray)">Assign TechTool</button>
      </div>
        </form>
         </div>
    </div>
  </div>
</div>

                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped " id="dataTable" width="100%"
                                       cellspacing="0">
                                    <thead class="bg-secondary text-light"   style=" background-image: linear-gradient(to right, darkslategray,#1a202c)">
                                    <tr>
                                        <th>Employee</th>
                                        <th>Designation</th>
                                        <th>Tech Tool</th>
                                        <th>Assign Date</th>
                                        <th>Submit Date</th>
                                        <th>Status</th>




                                    </tr>
                                    </thead>
                                    <tfoot class="bg-secondary text-light"   style=" background-image: linear-gradient(to right, darkslategray,#1a202c)">
                                    <tr>
                                        <th>Employee</th>
                                        <th>Designation</th>
                                        <th>Tech Tool</th>
                                        <th>Assign Date</th>
                                        <th>Submit Date</th>
                                         <th>Status</th>


                                    </tr>
                                    </tfoot>

                                    <tbody>
                                    {% for issued in issued_tools %}
                                        <tr>
                                            <td>{{ issued.empName }}</td>
                                            <td> {{ issued.empName.get_designation_display }}</td>
                                            <td>{{ issued.techTool }}</td>
                                            <td>{{ issued.borrowTime }}</td>
                                            <td>{{ issued.submitDate }}</td>
                                            {% if issued.timeOut is True %}
                                            <td class="text-danger">Time over</td>
                                                {% else %}
                                                <td class="text-success">success</td>
                                        {% endif %}
                                          </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>


    {% block js %}
        <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
        <script>
            $(document).ready(function () {
                $('#myTable').DataTable();
            });
        </script>


    {% endblock js %}
{% endblock %}